# NumPy Demo Matrix Operations
NumPy is a package for scientific computing with Python. This notebook has examples of matrix operations.

In [ ]:
import numpy as np

## Dot Product
Use np.dot() function to compute dot product of 1d arrays -> result is a scalar

In [ ]:
# X and Y are 1d arrays
# dot product 
X = np.array([1,2,3])
Y = np.array([4,5,6])
z = np.dot(X,Y)
print("z: {}".format(z))

Use np.dot() function to compute dot product of 2d row vector and 2d column vector -> result is a 2d array (1x1)

In [ ]:
# if X and Y are 2d arrays, then X needs to be a 2d row vector and Y needs to be a 2d column vector
# X = [1,2,3]
# Y = [4]
#     [5]
#     [6]
# X dot Y = [1,2,3] dot [4]
#                       [5]
#                       [6]
X = np.array([[1,2,3]])
Y = np.array([[4],[5],[6]])
print("X: {}".format(X))
print("Y: \n{}".format(Y))
z = np.dot(X,Y)
print("z: {}".format(z))
print("z.shape: {}".format(z.shape))

Use np.dot() function to compute dot product of 2d row vector and transpose of 2d column vector -> result is same as above

In [ ]:
# if X and Y are 2d arrays row vectors, then take transpose of Y (using .T attribute) before computing dot producct
# X = [1,2,3]
# Y = [4,5,6]
# X dot Y.T = [1,2,3] dot [4]
#                         [5]
#                         [6]
X = np.array([[1,2,3]])
Y = np.array([[4,5,6]])
print("X: {}".format(X))
print("Y.T: \n{}".format(Y.T))
z = np.dot(X,Y.T)
# result is a 1x1 array
print("z: {}".format(z))
print("z.shape: {}".format(z.shape))

Use np.dot() to compute transpose Y times X

In [ ]:
# # X and Y are 2d arrays row vector -> compute Y transpose dot X
# X = [1,2,3]
# Y = [4,5,6]
# 
# Y.T dot X = [4]  dot [1,2,3]
#             [5]
#             [6]
X = np.array([[1,2,3]])
Y = np.array([[4,5,6]])
print("X: {}".format(X))
print("Y.T: \n{}".format(Y.T))
z = np.dot(Y.T,X)
# result is a 3x3 array
print("z: \n{}".format(z))
print("z.shape: {}".format(z.shape))

## Matrix multiplication
Use np.matmul() function

In [ ]:
# X = [1 2]
#     [3 4]
# Y = [5 6]
#     [7 8]
X = np.array([[1,2],[3,4]])
Y = np.array([[5,6],[7,8]])
print("X: \n{}".format(X))
print("Y: \n{}".format(Y))
Z = np.matmul(X,Y)
# Z is a 2x2 array
print("Z = X Y: \n{}".format(Z))

Compute matrix multiplication: X transpose  S  X

In [ ]:
# if X is column vector and S is 3x3 matrix
# X = [1]
#     [2]
#     [3]
# S = [1 2 3]
#     [4 5 6]
#     [7 8 9]
# X.T S X = [1,2,3] [1 2 3] [1]
#                   [4 5 6] [2]
#                   [7 8 9] [3]
X = np.array([[1],[2],[3]])
S = np.array([[1,2,3],[4,5,6],[7,8,9]])
result = np.matmul(X.T,np.matmul(S,X))
print("X: \n{}".format(X))
print("S: \n{}".format(S))
print("X.T S X: {}".format(result))

## Matrix Inverse
use np.linalg.inv() function

In [ ]:
# X = [1, 2]
#     [4, 5]
X = np.array([[1,2],[4,5]])
Xinv = np.linalg.inv(X)
print("X: \n{}".format(X))
print("X inverse: \n{}".format(Xinv))
# confirm inverse calculation - should be identity
# X * Xinv
Confirm = np.matmul(X,Xinv)
print("Check X*Xinv: \n{}".format(Confirm))

## Determinant
use np.linalg.det() to compute determinant of a matrix

In [ ]:
# X = [1 2]
#     [3 4]
X = np.array([[1,2],[3,4]])
det = np.linalg.det(X)
print("determinant of X: \n{}".format(det))