# NumPy Matrix Operations Demo
NumPy is a package for scientific computing with Python. This notebook has examples of matrix operations.

In [1]:
import numpy as np

###  Dot Product of 1d arrays
Use np.dot() function to compute dot product of 1d arrays -> result is a scalar

In [4]:
# X and Y are 1d arrays
# dot product 
X = np.array([1,2,3])
Y = np.array([4,5,6])
z = np.dot(X,Y)
print("z: {}".format(z))

z: 32


### Dot product of 2d arrays
Use np.dot() function to compute dot product of 2d row vector and 2d column vector -> result is a 2d array (1x1)

In [5]:
# X = [1,2,3]
# Y = [4]
#     [5]
#     [6]
# X dot Y = [1,2,3] dot [4]
#                       [5]
#                       [6]
X = np.array([[1,2,3]])
Y = np.array([[4],[5],[6]])
print("X: {}".format(X))
print("Y: \n{}".format(Y))
z = np.dot(X,Y)
print("z: {}".format(z))
print("z.shape: {}".format(z.shape))

X: [[1 2 3]]
Y: 
[[4]
 [5]
 [6]]
z: [[32]]
z.shape: (1, 1)


In [6]:
# if X and Y are 2d arrays row vectors, then np.dot(X,Y) yields error (unless both are 1x1)
# number of columns of X must equal number of rows of Y for np.dot(X,Y) to work for 2d arrays
# X = [1,2,3]
# Y = [4,5,6]
# X dot Y = [1,2,3] dot [4,5,6]
X = np.array([[1,2,3]])
Y = np.array([[4,5,6]])
print("X: {}".format(X))
print("Y: {}".format(Y))
z = np.dot(X,Y)
print("z: {}".format(z))
print("z.shape: {}".format(z.shape))

X: [[1 2 3]]
Y: [[4 5 6]]


ValueError: shapes (1,3) and (1,3) not aligned: 3 (dim 1) != 1 (dim 0)

## Matrix multiplication
Use np.matmul() function

In [7]:
# X = [1 2]
#     [3 4]
# Y = [5 6]
#     [7 8]
X = np.array([[1,2],[3,4]])
Y = np.array([[5,6],[7,8]])
print("X: \n{}".format(X))
print("Y: \n{}".format(Y))
# Z = X * Y
Z = np.matmul(X,Y)
# Z is a 2x2 array
print("Z = X * Y: \n{}".format(Z))

X: 
[[1 2]
 [3 4]]
Y: 
[[5 6]
 [7 8]]
Z = X * Y: 
[[19 22]
 [43 50]]


Compute matrix multiplication: X transpose * S * X

In [8]:
# if X is column vector and S is 3x3 matrix
# X = [1]
#     [2]
#     [3]
# S = [1 2 3]
#     [4 5 6]
#     [7 8 9]
# X.T * S * X = [1,2,3] [1 2 3] [1]
#                       [4 5 6] [2]
#                       [7 8 9] [3]
X = np.array([[1],[2],[3]])
S = np.array([[1,2,3],[4,5,6],[7,8,9]])
result0 = np.matmul(X.T,np.matmul(S,X))
print("X: \n{}".format(X))
print("S: \n{}".format(S))
print("result0: X.T * S * X: {}".format(result0))

X: 
[[1]
 [2]
 [3]]
S: 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
result0: X.T * S * X: [[228]]


## Matrix Inverse
use np.linalg.inv() function

In [9]:
# X = [1, 2]
#     [4, 5]
X = np.array([[1,2],[4,5]])
print("X: \n{}".format(X))
Xinv = np.linalg.inv(X)
print("X inverse: \n{}".format(Xinv))
# confirm inverse calculation - should be identity
# X * Xinv
Confirm = np.matmul(X,Xinv)
print("Check X * Xinv: \n{}".format(Confirm))

X: 
[[1 2]
 [4 5]]
X inverse: 
[[-1.66666667  0.66666667]
 [ 1.33333333 -0.33333333]]
Check X * Xinv: 
[[1. 0.]
 [0. 1.]]


In [10]:
# Example of a singular matrix (non-invertible)
# X = [1, 2]
#     [1, 2]
X = np.array([[1,2],[1,2]])
print("X: \n{}".format(X))
Xinv = np.linalg.inv(X)
print("X inverse: \n{}".format(Xinv))

X: 
[[1 2]
 [1 2]]


LinAlgError: Singular matrix

## Determinant
use np.linalg.det() to compute determinant of a matrix

In [11]:
# X = [1 2]
#     [3 4]
X = np.array([[1,2],[3,4]])
det = np.linalg.det(X)
print("determinant of X: \n{}".format(det))

determinant of X: 
-2.0000000000000004
