# NumPy Basic Demo
NumPy is a package for scientific computing with Python. This notebook has examples of basic functionality.

In [ ]:
import numpy as np

## Array Creation and Indexing

In [ ]:
# array of integers 0 to 4 using arange (similar to python range)
a = np.arange(5)
print("a: {}".format(a))
print("Type: {}".format(type(a)))

In [ ]:
# create numpy array from a list
a = np.array([2,7,1])
print("1d array: a: {}".format(a))
print("1d array: a.shape: {}".format(a.shape))
print("Index into array entry index 2: {}".format(a[2]))

In [ ]:
# example: row vector vector as 2d array
# A = [2,7,1]
# Define A as list of list for each row
A = np.array([[2,7,1]])
print("2d row matrix: A: {}".format(A))
print("2d row matrix: A.shape: {}".format(A.shape))
print("Index into matrix entry index row=0,col=2: {}".format(A[0,2]))

In [ ]:
# example: 2d-array as column vector
# each row is a list
# Define B as list of list for each row
# B = [2]
#     [7]
#     [1]
B = np.array([[2],[7],[1]])
print("2d column matrix: B: \n{}".format(B))
print("2d column matrix: B.shape: {}".format(B.shape))
print("Index into matrix entry index row=1,col=0: {}".format(B[1,0]))

In [ ]:
# example: matrix
# X = [1 2 3]
#     [4 5 6]
# Define X as list of list for each row
X = np.array([[1,2,3],[4,5,6]])
print("2d array: X: \n{}".format(X))
print("2d array: X.shape: {}".format(X.shape))
print("Index into matrix entry index row=1,col=1: {}".format(X[1,1]))
print("Number of entries using np.size: {}".format(np.size(X)))

In [ ]:
# index into numpy array using list or array
idx_list = [1,2]
print("X: \n{}".format(X))
# index into row 0 cols [1,2]
print("X[0,[1,2]]: {}".format(X[0,idx_list]))
# index into cols [1,2] using a numpy array
idx_array = np.array([1,2])
print("X[:,[1,2]]: \n{}".format(X[:,idx_array]))

In [ ]:
# example: assign entry 17 to row=0,col=1 entry of X
X[0,1] = 17
print("X: \n{}".format(X))

In [ ]:
# example: assign [11,12,13] to row 1 of X
X[1,:] = np.array([[11,12,13]])
print("X: \n{}".format(X))

## Componentwise Operations
addition, multiplication, and scalar multiplication

In [ ]:
# X = [1 2 3]
#     [4 5 6]
# Y = [1 -1  2]
#     [2  3 -2]
X = np.array([[1,2,3],[4,5,6]])
Y = np.array([[1,-1,2],[2,3,-2]])
print("X: \n{}".format(X))
print("Y: \n{}".format(Y))

In [ ]:
#componentwise addition - add corresponding entries of X and Y
Z1 = X + Y
print("Z1=X+Y: \n{}".format(Z1))

In [ ]:
#scalar multiplication - multiply all entries of X by 2
Z2 = 2*X
print("Z2=2*X: \n{}".format(Z2))

In [ ]:
# componentwise multiplication - multiply corresponding entries of X and Y
Z3 = X*Y
print("X: \n{}".format(X))
print("Y: \n{}".format(Y))
print("Z3=X*Y: \n{}".format(Z3))

## Broadcasting
Componentwise addition of arrays of different size if calculation makes sense.
Same ideas apply to componentwise subtraction, multiplication, and division

In [ ]:
# X = [1 2 3]
#     [4 5 6]
# Y = [20,21,22]
# X + Y -> add Y to each row of X
X = np.array([[1,2,3],[4,5,6]])
Y = np.array([[20,21,22]])
Z = X + Y
print("x: \n{}".format(X))
print("Y: \n{}".format(Y))
print("Z: \n{}".format(Z))

## Functions
Examples include square, exp, sqrt, absolute value, power, ...

Take the absolute value of each element

In [ ]:
Y = np.array([[1,-1,2],[2,3,-2]])
Yabs = np.absolute(Y)
print("Y: \n{}".format(Y))
print("Absolute Value of Y: \n{}".format(Yabs))

Take the square of each element

In [ ]:
Xsq = np.square(X)
print("X: \n{}".format(X))
print("Square of X: \n{}".format(Xsq))

## where function

In [ ]:
# determine where a == 2
a = np.array([1,2,3,4,1,2,3,4])
idx = np.where(a == 2)[0]
print("a: {}".format(a))
print("indices where a = 2: {}".format(idx))

In [ ]:
# if there is potential for rounding error, use:
idx = np.where(np.absolute(a-2)<1e-5)[0]
print("indices where a = 2: {}".format(idx))

## Concatenation

In [ ]:
X = np.array([[1,2,3],[4,5,6]])
Y = np.array([[1,-1,2],[2,3,-2]])
print("X: \n{}".format(X))
print("Y: \n{}".format(Y))
# concatenation - in row direction - use axis=0 in 2nd input
# result is [1  2  3]
#           [4  5  6]
#           [1 -1  2]
#           [2  3 -2]
XandYrow = np.concatenate((X,Y),axis=0)
print("X and Y concatenated in row direction: \n{}".format(XandYrow))
# concatenation X and Y - in column direction - use axis=1 in 2nd input
# result is [1 2 3 1 -1  2]
#           [4 5 6 2  3 -2]
XandYcol = np.concatenate((X,Y),axis=1)
print("X and Y concatenated in column direction: \n{}".format(XandYcol))

## Reshape

In [ ]:
X = np.array([[1,2,3],[4,5,6]])
print("X: \n{}".format(X))
# reshape X into 3,2 array
Xreshape = np.reshape(X,(3,2))
print("Xreshape: \n{}".format(Xreshape))

## Summing Entries
same functionality for computing mean using np.mean

In [ ]:
# X = [1 2 3]
#     [4 5 6]
X = np.array([[1,2,3],[4,5,6]])
print("X: \n{}".format(X))
# sum all entries
sum1 = np.sum(X)
print("sum entries of x: {}".format(sum1))

In [ ]:
# sum in row direction - this removes an axis -> 1d array [5 7 9]
rowsum1 = np.sum(X,axis=0)
print("sum in row direction X: \n{}".format(rowsum1))
print("rowsum1.shape: {}".format(rowsum1.shape))

In [ ]:
# sum in row direction - keep row axis -> row matrix [5 7 9]
rowsum2 = np.sum(X,axis=0,keepdims=True)
print("sum in row direction X keep row axis: \n{}".format(rowsum2))
print("rowsum2.shape: {}".format(rowsum2.shape))

In [ ]:
# sum in column direction - keep column axis -> 2darray
colsum1 = np.sum(X,axis=1,keepdims=True)
print("sum in column direction keep col axis: \n{}".format(colsum1))
print("colsum1.shape: {}".format(colsum1.shape))

## max and argmax functions
similar functionality for np.min and np.argmin

In [ ]:
# X = [1.1 5.2 3.1]
#     [-4.2 -1.2 6.1]
X = np.array([[1.1,5.2,3.1],[-4.2,-1.2,6.1]])
print("X: \n{}".format(X))
# find maximum entry for each column (take max in "row" direction)
Xmax = np.max(X, axis =0)
print("X max for each column: {}".format(Xmax))
# find row index of maximum entry in each column (take argmax in "row" direction)
idx_argmax = np.argmax(X,axis=0)
print("index of max entry in each col: {}".format(idx_argmax))

## Array of Zeros
similar functionality for np.ones

In [ ]:
# generate zero matrix dimension (3,2)
Z0 = np.zeros((3,2))
print("zero matrix: \n{}".format(Z0))

## Array of Random Numbers

In [ ]:
# generate random matrix  dim (2,3) - uniform distribution
Runiform = np.random.rand(2,3)
print("Runiform: \n{}".format(Runiform))

In [ ]:
# generate random matrix  dim (2,3) - standard normal distribution
# set seed first
np.random.seed(10)
Rnormal = np.random.randn(2,3)
print("Rnormal: \n{}".format(Rnormal))

In [ ]:
# random 1d array of 15 random integers between 0 and 9
Rint = np.random.randint(0,10,15)
print("Random integers: {}".format(Rint))

In [ ]:
# 1d numpy array of 7 numbers randomly chosen from Rint = [0,1,2,...,9]
Rint = np.arange(10)
print("Rint: {}".format(Rint))
Rchoice = np.random.choice(Rint,7,replace=False)
print("Rchoice: {}".format(Rchoice))