# NumPy Basic Demo
NumPy is a package for scientific computing with Python. This notebook has examples of basic functionality.

In [1]:
import numpy as np

## Array Creation and Indexing

In [2]:
# convert list to numpy array
a = np.array([2,7,1])
print("1d array: a: {}".format(a))
print("1d array: a.shape: {}".format(a.shape))
print("Index into array entry index 2: {}".format(a[2]))

1d array: a: [2 7 1]
1d array: a.shape: (3,)
Index into array entry index 2: 1


In [3]:
# example: 2d-array as row vector
# A = [2,7,1]
# Define A as list of list for each row
A = np.array([[2,7,1]])
print("2d row matrix: A: {}".format(A))
print("2d row matrix: A.shape: {}".format(A.shape))
print("Index into matrix entry index row=0,col=2: {}".format(A[0,2]))

2d row matrix: A: [[2 7 1]]
2d row matrix: A.shape: (1, 3)
Index into matrix entry index row=0,col=2: 1


In [4]:
# example: 2d-array as column vector
# each row is a list
# Define B as list of list for each row
# B = [2]
#     [7]
#     [1]
B = np.array([[2],[7],[1]])
print("2d column matrix: B: \n{}".format(B))
print("2d column matrix: B.shape: {}".format(B.shape))
print("Index into matrix entry index row=1,col=0: {}".format(B[1,0]))

2d column matrix: B: 
[[2]
 [7]
 [1]]
2d column matrix: B.shape: (3, 1)
Index into matrix entry index row=1,col=0: 7


In [5]:
# example: matrix
# X = [1 2 3]
#     [4 5 6]
# Define X as list of list for each row
X = np.array([[1,2,3],[4,5,6]])
print("2d array: X: \n{}".format(X))
print("2d array: X.shape: {}".format(X.shape))
print("Index into matrix entry index row=1,col=1: {}".format(X[1,1]))

2d array: X: 
[[1 2 3]
 [4 5 6]]
2d array: X.shape: (2, 3)
Index into matrix entry index row=1,col=1: 5


In [6]:
# example: assign entry 17 to row=0,col=1 entry of X
X[0,1] = 17
print("X: \n{}".format(X))

X: 
[[ 1 17  3]
 [ 4  5  6]]


In [7]:
# example: assign [11,12,13] to row 1 of X
X[1,:] = np.array([[11,12,13]])
print("X: \n{}".format(X))

X: 
[[ 1 17  3]
 [11 12 13]]


## Componentwise Operations
addition, multiplication, and scalar multiplication

In [8]:
# X = [1 2 3]
#     [4 5 6]
# Y = [1 -1  2]
#     [2  3 -2]
X = np.array([[1,2,3],[4,5,6]])
Y = np.array([[1,-1,2],[2,3,-2]])
print("X: \n{}".format(X))
print("Y: \n{}".format(Y))

X: 
[[1 2 3]
 [4 5 6]]
Y: 
[[ 1 -1  2]
 [ 2  3 -2]]


In [9]:
#componentwise addition - add corresponding entries of X and Y
Z1 = X + Y
print("Z1=X+Y: \n{}".format(Z1))

Z1=X+Y: 
[[2 1 5]
 [6 8 4]]


In [10]:
#scalar multiplication - multiply all entries of X by 2
Z2 = 2*X
print("Z2=2*X: \n{}".format(Z2))

Z2=2*X: 
[[ 2  4  6]
 [ 8 10 12]]


In [11]:
# componentwise multiplication - multiply corresponding entries of X and Y
Z3 = X*Y
print("X: \n{}".format(X))
print("Y: \n{}".format(Y))
print("Z3=X*Y: \n{}".format(Z3))

X: 
[[1 2 3]
 [4 5 6]]
Y: 
[[ 1 -1  2]
 [ 2  3 -2]]
Z3=X*Y: 
[[  1  -2   6]
 [  8  15 -12]]


## Broadcasting
Componentwise addition of arrays of different size if calculation makes sense.
Same ideas apply to componentwise subtraction, multiplication, and division

In [14]:
# X = [1 2 3]
#     [4 5 6]
# Y = [20,21,22]
# X + Y -> add Y to each row of X
X = np.array([[1,2,3],[4,5,6]])
Y = np.array([[20,21,22]])
Z = X + Y
print("x: \n{}".format(X))
print("Y: \n{}".format(Y))
print("Z: \n{}".format(Z))

x: 
[[1 2 3]
 [4 5 6]]
Y: 
[[20 21 22]]
Z: 
[[21 23 25]
 [24 26 28]]


## Functions

### Absolute Value
Take the abslute value of each element

In [15]:
Y = np.array([[1,-1,2],[2,3,-2]])
Yabs = np.absolute(Y)
print("Y: \n{}".format(Y))
print("Absolute Value of Y: \n{}".format(Yabs))

Y: 
[[ 1 -1  2]
 [ 2  3 -2]]
Absolute Value of Y: 
[[1 1 2]
 [2 3 2]]


### Square
Take the square of each element

In [17]:
Xsq = np.exp(X)
print("X: \n{}".format(X))
print("Square of X: \n{}".format(Xsq))

X: 
[[1 2 3]
 [4 5 6]]
Square of X: 
[[  2.71828183   7.3890561   20.08553692]
 [ 54.59815003 148.4131591  403.42879349]]


## Concatenation

In [18]:
X = np.array([[1,2,3],[4,5,6]])
Y = np.array([[1,-1,2],[2,3,-2]])
print("X: \n{}".format(X))
print("Y: \n{}".format(Y))
# concatenation - in row direction - use axis=0 in 2nd input
# result is [1  2  3]
#           [4  5  6]
#           [1 -1  2]
#           [2  3 -2]
XandYrow = np.concatenate((X,Y),axis=0)
print("X and Y concatenated in row direction: \n{}".format(XandYrow))
# concatenation X and Y - in column direction - use axis=1 in 2nd input
# result is [1 2 3 1 -1  2]
#           [4 5 6 2  3 -2]
XandYcol = np.concatenate((X,Y),axis=1)
print("X and Y concatenated in column direction: \n{}".format(XandYcol))

X: 
[[1 2 3]
 [4 5 6]]
Y: 
[[ 1 -1  2]
 [ 2  3 -2]]
X and Y concatenated in row direction: 
[[ 1  2  3]
 [ 4  5  6]
 [ 1 -1  2]
 [ 2  3 -2]]
X and Y concatenated in column direction: 
[[ 1  2  3  1 -1  2]
 [ 4  5  6  2  3 -2]]


## Summing Entries

In [19]:
# X = [1 2 3]
#     [4 5 6]
X = np.array([[1,2,3],[4,5,6]])
print("X: \n{}".format(X))
# sum all entries
sum1 = np.sum(X)
print("sum entries of x: {}".format(sum1))

X: 
[[1 2 3]
 [4 5 6]]
sum entries of x: 21


In [20]:
# sum in row direction - this removes an axis -> 1d array [5 7 9]
rowsum1 = np.sum(X,axis=0)
print("sum in row direction X: \n{}".format(rowsum1))
print("rowsum1.shape: {}".format(rowsum1.shape))

sum in row direction X: 
[5 7 9]
rowsum1.shape: (3,)


In [21]:
# sum in row direction - keep row axis -> row matrix [5 7 9]
rowsum2 = np.sum(X,axis=0,keepdims=True)
print("sum in row direction X keep row axis: \n{}".format(rowsum2))
print("rowsum2.shape: {}".format(rowsum2.shape))

sum in row direction X keep row axis: 
[[5 7 9]]
rowsum2.shape: (1, 3)


In [22]:
# sum in column direction - keep column axis -> 2darray
colsum1 = np.sum(X,axis=1,keepdims=True)
print("sum in column direction keep col axis: \n{}".format(colsum1))
print("colsum1.shape: {}".format(colsum1.shape))

sum in column direction keep col axis: 
[[ 6]
 [15]]
colsum1.shape: (2, 1)


## Array of Zeros

In [23]:
# generate zero matrix dimension (3,2)
Z0 = np.zeros((3,2))
print("zero matrix: \n{}".format(Z0))

zero matrix: 
[[0. 0.]
 [0. 0.]
 [0. 0.]]


## Array of Random Numbers

In [25]:
# generate random matrix  dim (2,3) - uniform distribution
Runiform = np.random.rand(2,3)
print("Runiform: \n{}".format(Runiform))

Runiform: 
[[0.38357367 0.67000952 0.24068845]
 [0.21999931 0.0439532  0.00100496]]


In [26]:
# generate random matrix  dim (2,3) - standard normal distribution
# set seed first
np.random.seed(10)
Rnormal = np.random.randn(2,3)
print("Rnormal: \n{}".format(Rnormal))

Rnormal: 
[[ 1.3315865   0.71527897 -1.54540029]
 [-0.00838385  0.62133597 -0.72008556]]
