# NumPy Demo
NumPy is a package for scientific computing with Python.

In [ ]:
import numpy as np

## Array Creation and Indexing

In [ ]:
# convert list to numpy array
a = np.array([2,7,1])
print("1d array: a: {}".format(a))
print("1d array: a.shape: {}".format(a.shape))
print("Index into array entry index 2: {}".format(a[2]))

In [ ]:
# example: 2d-array as row vector
# A = [2,7,1]
# Define A as list of list for each row
A = np.array([[2,7,1]])
print("2d row matrix: A: {}".format(A))
print("2d row matrix: A.shape: {}".format(A.shape))
print("Index into matrix entry index row=0,col=2: {}".format(A[0,2]))

In [ ]:
# example: 2d-array as column vector
# each row is a list
# Define B as list of list for each row
# B = [2]
#     [7]
#     [1]
B = np.array([[2],[7],[1]])
print("2d column matrix: B: \n{}".format(B))
print("2d column matrix: B.shape: {}".format(B.shape))
print("Index into matrix entry index row=1,col=0: {}".format(B[1,0]))

In [ ]:
# example: matrix
# X = [1 2 3]
#     [4 5 6]
# Define X as list of list for each row
X = np.array([[1,2,3],[4,5,6]])
print("2d array: X: \n{}".format(X))
print("2d array: X.shape: {}".format(X.shape))
print("Index into matrix entry index row=1,col=1: {}".format(X[1,1]))

## Component-wise Operations

In [ ]:
# X = [1 2 3]
#     [4 5 6]
# Y = [1 -1  2]
#     [2  3 -2]
X = np.array([[1,2,3],[4,5,6]])
Y = np.array([[1,-1,2],[2,3,-2]])
print("X: \n{}".format(X))
print("Y: \n{}".format(Y))

### Component-wise Addition
Component-wise addition, the result will be an array of the same dimension as the inputs

In [ ]:
Z1 = X + Y
print("Z1=X+Y: \n{}".format(Z1))

### Scalar Multiplication
Multiply each element by a scalar

In [ ]:
Z2 = 2*X
print("Z2=2*X: \n{}".format(Z2))

### Component-wise Multipication
Component-wise multiplication (this is not matrix multiplication), the result will be an array of the same dimension as the inputs

In [ ]:
Z3 = X*Y
print("X: \n{}".format(X))
print("Y: \n{}".format(Y))
print("Z3=X*Y: \n{}".format(Z3))

## Functions

### Absolute Value
Take the abslute value of each element

In [ ]:
Yabs = np.absolute(Y)
print("Y: \n{}".format(Y))
print("Absolute Value of Y: \n{}".format(Yabs))

### Square
Take the square of each element

In [ ]:
Xsq = np.square(X)
print("X: \n{}".format(X))
print("Square of X: \n{}".format(Xsq))

## Concatenation

In [ ]:
X = np.array([[1,2,3],[4,5,6]])
Y = np.array([[1,-1,2],[2,3,-2]])
print("X: \n{}".format(X))
print("Y: \n{}".format(Y))
# concatenation - in row direction - use axis=0 in 2nd input
# result is [1  2  3]
#           [4  5  6]
#           [1 -1  2]
#           [2  3 -2]
XandYrow = np.concatenate((X,Y),axis=0)
print("X and Y concatenated in row direction: \n{}".format(XandYrow))
# concatenation X and Y - in column direction - use axis=1 in 2nd input
# result is [1 2 3 1 -1  2]
#           [4 5 6 2  3 -2]
XandYcol = np.concatenate((X,Y),axis=1)
print("X and Y concatenated in column direction: \n{}".format(XandYcol))

## Summing Entries

In [ ]:
# X = [1 2 3]
#     [4 5 6]
X = np.array([[1,2,3],[4,5,6]])
print("X: \n{}".format(X))
# sum all entries
sum1 = np.sum(X)
print("sum entries of x: {}".format(sum1))

In [ ]:
# sum in row direction - this removes an axis -> 1d array [5 7 9]
rowsum1 = np.sum(X,axis=0)
print("sum in row direction X: \n{}".format(rowsum1))
print("rowsum1.shape: {}".format(rowsum1.shape))

In [ ]:
# sum in row direction - keep row axis -> row matrix [5 7 9]
rowsum2 = np.sum(X,axis=0,keepdims=True)
print("sum in row direction X keep row axis: \n{}".format(rowsum2))
print("rowsum2.shape: {}".format(rowsum2.shape))

In [ ]:
# sum in column direction - keep column axis -> 2darray
colsum1 = np.sum(X,axis=1,keepdims=True)
print("sum in column direction keep col axis: \n{}".format(colsum1))
print("colsum1.shape: {}".format(colsum1.shape))

## Array of Zeros

In [ ]:
# generate zero matrix dimension (3,2)
Z0 = np.zeros((3,2))
print("zero matrix: \n{}".format(Z0))

## Array of Random Numbers

In [ ]:
# generate random matrix  dim (2,3) - uniform distribution
Runiform = np.random.rand(2,3)
print("Runiform: \n{}".format(Runiform))

In [ ]:
# generate random matrix  dim (2,3) - normal distribution
# set seed first
np.random.seed(10)
Rnormal = np.random.randn(2,3)
print("Rnormal: \n{}".format(Rnormal))